(defvar text_task ())
(defun $solve_q_eq (a b c)
	(($MPLUS) a b c)
)
(defun $foo (x) (format t "~a~%" x))
(defun $readlinestdio () (read-line))
;(defun $compile_tex_file (fname) (EXT:SHELL (format nil "pdflatex ~a.tex" fname)))
